max_width = 80
unstable_features = true
imports_granularity = "Crate"
use_field_init_shorthand = true
reorder_impl_items = true
wrap_comments = true
format_code_in_doc_comments = true
newline_style = "Unix"
